language: python
python:
  - '3.6'
install:
  - pip3 install -e .
before_script:
  - pip3 install coveralls
  - pip3 install scipy
  - pip3 install edlib
  - pip3 install matplotlib
script:
  - coverage run -m unittest
after_success:
  - coveralls
